### ISSUE TITLE
Vos rapports

### ISSUE THREAD

**Issue by Apter-X** [Apter-X/Photoshop-Web-Design#25]
Certains rapports manque ?

**Comment by ayoubessafi** [comment]
il n'est pas accepter pull request, il dit une conflits 
j’envoie le rapport sur boite e-mail

**Comment by ayoubessafi** [comment]
le message qui afficher:  Can’t automatically merge. Don’t worry, you can still create the pull request.

**Comment by Apter-X** [comment]
@ayoubessafi le conflit est au niveau du nom de ton fichier car tu l'as nommé "image_01", et il existe deja un fichier du même nom. Change le nom de ton fichier par ton nom et prenom et ça devrait marcher sans conflit.
